'use client';

import Link from 'next/link';
import { useTranslation } from 'react-i18next';
import { ChefHat, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';

export default function TermsPage() {
  const { i18n } = useTranslation();
  const lang = i18n.language as 'es' | 'en';

  const content = {
    es: {
      title: 'Términos de Uso',
      lastUpdated: 'Última actualización: Enero 2026',
      sections: [
        {
          title: '1. Aceptación de Términos',
          content: 'Al usar Smart Cookbook, aceptas estos términos de uso. Si no estás de acuerdo con alguno de ellos, por favor no utilices la aplicación.',
        },
        {
          title: '2. Descripción del Servicio',
          content: 'Smart Cookbook es una aplicación web que genera recetas personalizadas usando inteligencia artificial. El servicio es gratuito y no requiere registro. Todas las funcionalidades operan 100% en tu navegador.',
        },
        {
          title: '3. Uso de API Keys',
          content: 'Para generar recetas, necesitas proporcionar una API key de un proveedor de IA compatible. Tus API keys se almacenan EXCLUSIVAMENTE en tu navegador (localStorage). Nosotros nunca tenemos acceso a ellas. Eres responsable de mantener la seguridad de tus API keys.',
        },
        {
          title: '4. Contenido Generado por IA',
          content: 'Las recetas son generadas por modelos de inteligencia artificial y pueden contener errores. SIEMPRE debes: verificar los ingredientes según tus alergias y restricciones, usar tu criterio antes de cocinar cualquier receta, y consultar a un profesional de salud si tienes dudas sobre ingredientes específicos.',
        },
        {
          title: '5. Limitación de Responsabilidad',
          content: 'Smart Cookbook se proporciona "tal cual" sin garantías de ningún tipo. No somos responsables de: reacciones alérgicas o problemas de salud derivados del consumo de recetas generadas, costos asociados al uso de API keys de terceros, pérdida de datos almacenados en tu navegador.',
        },
        {
          title: '6. Privacidad',
          content: 'No recopilamos datos personales. Todo se almacena localmente en tu dispositivo. Consulta nuestra Política de Privacidad para más detalles.',
        },
        {
          title: '7. Modificaciones',
          content: 'Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios serán efectivos inmediatamente después de su publicación.',
        },
        {
          title: '8. Contacto',
          content: 'Para cualquier duda sobre estos términos, puedes contactarnos a través de GitHub.',
        },
      ],
    },
    en: {
      title: 'Terms of Use',
      lastUpdated: 'Last updated: January 2026',
      sections: [
        {
          title: '1. Acceptance of Terms',
          content: 'By using Smart Cookbook, you accept these terms of use. If you do not agree with any of them, please do not use the application.',
        },
        {
          title: '2. Service Description',
          content: 'Smart Cookbook is a web application that generates personalized recipes using artificial intelligence. The service is free and requires no registration. All features operate 100% in your browser.',
        },
        {
          title: '3. API Key Usage',
          content: 'To generate recipes, you need to provide an API key from a compatible AI provider. Your API keys are stored EXCLUSIVELY in your browser (localStorage). We never have access to them. You are responsible for maintaining the security of your API keys.',
        },
        {
          title: '4. AI-Generated Content',
          content: 'Recipes are generated by artificial intelligence models and may contain errors. You should ALWAYS: verify ingredients according to your allergies and restrictions, use your judgment before cooking any recipe, and consult a health professional if you have questions about specific ingredients.',
        },
        {
          title: '5. Limitation of Liability',
          content: 'Smart Cookbook is provided "as is" without warranties of any kind. We are not responsible for: allergic reactions or health problems resulting from consumption of generated recipes, costs associated with the use of third-party API keys, loss of data stored in your browser.',
        },
        {
          title: '6. Privacy',
          content: 'We do not collect personal data. Everything is stored locally on your device. See our Privacy Policy for more details.',
        },
        {
          title: '7. Modifications',
          content: 'We reserve the right to modify these terms at any time. Changes will be effective immediately upon publication.',
        },
        {
          title: '8. Contact',
          content: 'For any questions about these terms, you can contact us through GitHub.',
        },
      ],
    },
  };

  const t = content[lang];

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-yellow-50 dark:from-gray-900 dark:to-gray-800">
      <div className="max-w-3xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Link href="/">
            <Button variant="ghost" size="sm" icon={<ArrowLeft className="h-4 w-4" />}>
              {lang === 'es' ? 'Volver' : 'Back'}
            </Button>
          </Link>
          <div className="flex items-center gap-2">
            <ChefHat className="h-6 w-6 text-orange-500" />
            <span className="font-bold text-gray-900 dark:text-white">Smart Cookbook</span>
          </div>
        </div>

        {/* Content */}
        <Card>
          <CardContent className="p-8">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
              📜 {t.title}
            </h1>
            <p className="text-sm text-gray-500 mb-8">{t.lastUpdated}</p>

            <div className="space-y-6">
              {t.sections.map((section, index) => (
                <div key={index}>
                  <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                    {section.title}
                  </h2>
                  <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                    {section.content}
                  </p>
                </div>
              ))}
            </div>

            {/* Footer links */}
            <div className="mt-12 pt-6 border-t border-gray-200 dark:border-gray-700 flex gap-4 text-sm">
              <Link href="/privacy" className="text-orange-600 hover:underline">
                {lang === 'es' ? 'Privacidad' : 'Privacy'}
              </Link>
              <Link href="/disclaimer" className="text-orange-600 hover:underline">
                Disclaimer
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
